#! /bin/sh
PATH=~/.xmonad/scripts:/bin

lbody(){
  for dtno in {1..12}
  do case $dtno in 
        1|2|8) continue;;
        10) continue;;
        *) xmonadctl -a goto $dtno
           sleep 10;;
     esac
  done
 }


while :
do lbody
    sleep $((10 * 1))
done
